---
name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1
      - name: Install python
        uses: actions/setup-python@v3
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

  test-install-from-source:
    name: Test PostgreSQL ${{ matrix.pg }} source install on Ubuntu ${{ matrix.release }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        pg: ['11', '12', '13', '14', '15']
        release: [focal, jammy]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Build Docker container
        run: docker build --build-arg=RELEASE=${{ matrix.release }} --tag=tester .

      - name: Install from source
        run: docker run --rm tester ./test/ci/install-from-source.bash
